# -*- coding: utf-8 -*-
# Created by: PyQt5 UI code generator 5.15.4

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlgorithmEditor(QtWidgets.QMainWindow):
    resized = QtCore.pyqtSignal()
    def __init__(self):
        super(self.__class__, self).__init__()
        self.setObjectName("AlgorithmEditor")
        self.resize(800,500)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout()
        self.horizontalLayout_main.setSpacing(0)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.verticalLayout_leftMenu = QtWidgets.QVBoxLayout()
        self.verticalLayout_leftMenu.setContentsMargins(-1, 5, -1, 0)
        self.verticalLayout_leftMenu.setSpacing(0)
        self.verticalLayout_leftMenu.setObjectName("verticalLayout_leftMenu")
        self.label_alglist = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        # font.setUnderline(True)
        font.setBold(True)
        self.label_alglist.setFont(font)
        self.label_alglist.setAlignment(QtCore.Qt.AlignCenter)
        self.label_alglist.setObjectName("label_alglist")
        self.verticalLayout_leftMenu.addWidget(self.label_alglist)
        self.scrollArea_algorithms = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_algorithms.sizePolicy().hasHeightForWidth())
        self.scrollArea_algorithms.setSizePolicy(sizePolicy)
        self.scrollArea_algorithms.setStyleSheet("border-width: 0px; border-style: solid;\n"
"")
        self.scrollArea_algorithms.setWidgetResizable(True)
        self.scrollArea_algorithms.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scrollArea_algorithms.setObjectName("scrollArea_algorithms")
        self.scrollAreaWidgetContents_buttonsAlgs = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_buttonsAlgs.setGeometry(QtCore.QRect(0, 0, 129, 46))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_buttonsAlgs.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_buttonsAlgs.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_buttonsAlgs.setObjectName("scrollAreaWidgetContents_buttonsAlgs")
        self.verticalLayout_buttonsAlgs = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_buttonsAlgs)
        self.verticalLayout_buttonsAlgs.setContentsMargins(2, 5, 2, 5)
        self.verticalLayout_buttonsAlgs.setSpacing(4)
        self.verticalLayout_buttonsAlgs.setObjectName("verticalLayout_buttonsAlgs")
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(False)

        self.algfont = font

        self.scrollArea_algorithms.setWidget(self.scrollAreaWidgetContents_buttonsAlgs)
        self.verticalLayout_leftMenu.addWidget(self.scrollArea_algorithms)

        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)

        # Create button
        self.pushButton_createAlg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_createAlg.setFont(font)
        self.pushButton_createAlg.setStyleSheet("color: rgb(0, 130, 0);")
        self.pushButton_createAlg.setObjectName("pushButton_createAlg")
        self.verticalLayout_leftMenu.addWidget(self.pushButton_createAlg)

        # Delete button
        self.pushButton_deleteAlg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_deleteAlg.setFont(font)
        self.pushButton_deleteAlg.setStyleSheet("color: rgb(222, 0, 0);")
        self.pushButton_deleteAlg.setObjectName("pushButton_deleteAlg")
        self.verticalLayout_leftMenu.addWidget(self.pushButton_deleteAlg)
        self.pushButton_useAlg = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_useAlg.sizePolicy().hasHeightForWidth())
        self.pushButton_useAlg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_useAlg.setFont(font)
        self.pushButton_useAlg.setObjectName("pushButton_useAlg")
        self.verticalLayout_leftMenu.addWidget(self.pushButton_useAlg)
        self.horizontalLayout_main.addLayout(self.verticalLayout_leftMenu)
        self.verticalLayout_rightMenu = QtWidgets.QVBoxLayout()
        self.verticalLayout_rightMenu.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_rightMenu.setContentsMargins(5, -1, 0, -1)
        self.verticalLayout_rightMenu.setSpacing(0)
        self.verticalLayout_rightMenu.setObjectName("verticalLayout_rightMenu")
        self.lineEdit_algName = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono ExtraLight")
        font.setPointSize(11)
        self.lineEdit_algName.setFont(font)
        self.lineEdit_algName.setStyleSheet("border-width: 0px; border-style: solid; \n"
"background-color: rgb(240, 240, 240);")
        self.lineEdit_algName.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_algName.setObjectName("lineEdit_algName")
        self.verticalLayout_rightMenu.addWidget(self.lineEdit_algName)
        self.scrollArea_algEditor = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_algEditor.setStyleSheet("border-width: 0px; border-style: solid;")
        self.scrollArea_algEditor.setWidgetResizable(True)
        self.scrollArea_algEditor.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_algEditor.setObjectName("scrollArea_algEditor")
        self.scrollAreaWidgetContents_algEditor = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_algEditor.setGeometry(QtCore.QRect(0, 0, 651, 536))
        self.scrollAreaWidgetContents_algEditor.setObjectName("scrollAreaWidgetContents_algEditor")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_algEditor)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit_algEditor = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_algEditor)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit_algEditor.setFont(font)
        self.textEdit_algEditor.setStyleSheet("border-color: rgb(0, 0, 0);border-width: 1px;")
        self.textEdit_algEditor.setObjectName("textEdit_algEditor")
        self.textEdit_algEditor.setTabStopDistance(
            QtGui.QFontMetricsF(self.textEdit_algEditor.font()).horizontalAdvance(' ') * 4)
        self.verticalLayout_3.addWidget(self.textEdit_algEditor)
        self.scrollArea_algEditor.setWidget(self.scrollAreaWidgetContents_algEditor)
        self.verticalLayout_rightMenu.addWidget(self.scrollArea_algEditor)
        self.horizontalLayout_saveButtonSpacer = QtWidgets.QHBoxLayout()
        self.horizontalLayout_saveButtonSpacer.setContentsMargins(7, -1, 7, -1)
        self.horizontalLayout_saveButtonSpacer.setSpacing(0)
        self.horizontalLayout_saveButtonSpacer.setObjectName("horizontalLayout_saveButtonSpacer")
        self.pushButton_saveAlg = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_saveAlg.setFont(font)
        self.pushButton_saveAlg.setObjectName("pushButton_saveAlg")
        self.horizontalLayout_saveButtonSpacer.addWidget(self.pushButton_saveAlg)
        self.verticalLayout_rightMenu.addLayout(self.horizontalLayout_saveButtonSpacer)
        self.horizontalLayout_main.addLayout(self.verticalLayout_rightMenu)
        self.horizontalLayout_main.setStretch(0, 1)
        self.horizontalLayout_main.setStretch(1, 5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_main)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("AlgorithmEditor", "MainWindow"))
        self.label_alglist.setText(_translate("AlgorithmEditor", "Saved algorithms"))
        self.pushButton_createAlg.setText(_translate("AlgorithmEditor", "Create new"))
        self.pushButton_deleteAlg.setText(_translate("AlgorithmEditor", "Delete"))
        self.pushButton_useAlg.setText(_translate("AlgorithmEditor", "Use"))
        self.textEdit_algEditor.setText(_translate("AlgorithmEditor", "Select an algorithm to edit the code."))

        self.pushButton_saveAlg.setText(_translate("AlgorithmEditor", "Save"))

    def resizeEvent(self, event):
        self.resized.emit()

        return super(self.__class__, self).resizeEvent(event)
